# Generated by Django 5.1.1 on 2024-09-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('observations', models.TextField()),
                ('notes', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('test_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('observations', models.TextField()),
                ('date_conducted', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('pathologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.pathologist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.tests')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermRecord',
            fields=[
                ('long_term_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
                ('test_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.testreport')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.medicines')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'medicine')},
            },
        ),
        migrations.CreateModel(
            name='TestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.prescription')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.tests')),
            ],
            options={
                'unique_together': {('test', 'prescription')},
            },
        ),
    ]
