# Generated by Django 5.1.1 on 2024-09-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('granted', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_granted', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('permission_type', models.CharField(choices=[('View', 'View'), ('Add', 'Add'), ('Modify', 'Modify')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('access_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_accessed', models.DateTimeField(auto_now_add=True)),
                ('justification_submitted', models.BooleanField(default=False)),
                ('justification_text', models.TextField(blank=True, null=True)),
                ('admin_notified', models.BooleanField(default=False)),
                ('patient_notified', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAccessRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=15)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.insurancecompany')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LegalAccessRequest',
            fields=[
                ('legal_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('warrant_document', models.FileField(blank=True, null=True, upload_to='warrants/')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=15)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.admin')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.lawenforcementagency')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RecordDeletionRequest',
            fields=[
                ('deletion_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('Prescription', 'Prescription'), ('TestReport', 'TestReport'), ('LongTermRecord', 'LongTermRecord')], max_length=20)),
                ('record_id', models.IntegerField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=15)),
                ('reason', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.admin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
    ]
